name: Publish

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - name: Publish
        run: cargo publish -p garnish_lang_utilities
